export const ADMIN_SOLVER_ERROR_WINDOW_MINUTES = 15;
export const ADMIN_SOLVER_TREND_WINDOW_MINUTES = 60;
export const ADMIN_SOLVER_TREND_BUCKET_MINUTES = 5;
export const ADMIN_SOLVER_METRICS_REFRESH_INTERVAL_SECONDS = 10;
